---@class ua.info
---@field m ua.object
---@field line string
---@field col number
---@field gsave table
---@field lsave table
---@class ua.act
---@field [1] 'left'|'right'|'pos'
---@field [number] any
---@alias ua.actions (string|ua.act)[]
---@class ua.object
---@field run? fun(o:ua.info):ua.actions?
---@field hooks ua.hook.hash[]
---@field __hook_subconf ua.hook.subconf
---@field doc? string
---@alias ua.id number
---@alias ua.prof.conf table
---@class ua.hook
---@field input string
---@field type string
---@field mode string
---@alias ua.hook.hash string
---@alias ua.hook.conf string
---@alias ua.hook.subconf string
---@class ua.hook.info
---@field [number] ua.object
---@field dirty boolean?
---@field conf ua.hook.conf?
---TODO: request options
----@field expr boolean --only for type=map, use expr or not
----@field feed boolean --only for type=map;expr=false, use nvim_feedkeys instead of using functions to go to places
----@field true_dot boolean --only for type=map;expr=true,to prioritize dot repeat above all else, basically only allow <arrow> for movement, no <C-o>...
